### ISSUE TITLE
not working with debug mode with codeceptjs

### ISSUE THREAD

**Issue by vitaly87** [codecept-js/codeceptjs-resemblehelper#29]
cant work with debug mode getting errors:

the conf codeceptjs :

`  ResembleHelper: {
      require: "codeceptjs-resemblehelper",
      screenshotFolder: "./output/",
      baseFolder: "./tests/visual-testing/screenshots/base/",
      diffFolder: "./output/diff/"
    }`
the error:

`Could not load helper ResembleHelper from module 'codeceptjs-resemblehelper':
Cannot find module 'codeceptjs-resemblehelper'`

`test-assets\codeceptjs\node_modules\codeceptjs\lib\container.js:153:13)`

codeceptjs version 2.1.3

**Comment by Kartikeya99** [comment]
Can you please paste your whole configuration file?

**Comment by vitaly87** [comment]
if not debug mode its working if its debug mode then no

**Comment by Kartikeya99** [comment]
Are you running `codeceptjs run --debug` ?

**Comment by vitaly87** [comment]
nope. i configer to run codecptjs with debug that means working with nodejs with breakpoints

**Comment by puneet0191** [comment]
@vitaly87  please check latest, if you still find issues, I will reopen.
