### ISSUE TITLE
Not installed on MAC ERR! canvas@2.6.0

### ISSUE THREAD

**Issue by SokolovAlex** [codecept-js/codeceptjs-resemblehelper#45]
try to install package on MAC

npm install codeceptjs-resemblehelper
npm install --build-from-source codeceptjs-resemblehelper

and see this error

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.0 install: `node-pre-gyp install --fallback-to-build`

what's wrong?

**Comment by puneet0191** [comment]
thanks for reporting this, I will look into it and get back

**Comment by puneet0191** [comment]
@SokolovAlex are you still facing this? because I am trying to use with canvas@2.6.1 and it seems to work fine for me, please confirm back if you still face this issue, try updating to canvas@2.6.1

**Comment by SokolovAlex** [comment]
i m not use resemblehelper now. if problem not  repeated, i close issue
