### ISSUE TITLE
Add custom assert message

### ISSUE THREAD

**Issue by leonardonelson91** [codecept-js/codeceptjs-resemblehelper#48]
Hi, it would be nice to have the ability to provide a custom assert error message on the visualDiff functions, so that it looks better in the reports.

**Current assert error message:**
`MissMatch Percentage 1.86
      + expected - actual
      -false
      +true`

**Desired assert error message example:**
`
      Images A and B do not match. (MissMatch Percentage 1.86)
      + expected - actual
      -false
      +true
`

**Comment by puneet0191** [comment]
Sure, go ahead and help with the Patch if you can :) otherwise I look into it in some days, thanks a lot
