### ISSUE TITLE
The tests passes even when it is over threshold.

### ISSUE THREAD

**Issue by vazsonyidl** [codecept-js/codeceptjs-resemblehelper#71]
Hi there,

```
if (options.skipFailure === false) {
      assert(misMatch <= options.tolerance, "Screenshot does not match with the baseline " + baseImage + " when MissMatch Percentage is " + misMatch);
    }
```

As the previous code snippet shows, since the options.skipFailure is undefined, the comparison would always return false. Because of this, the `assert` would never run, and the pipeline passes even when the tolerance is clearly over the threshold.

Please define false as default, because previously the `assert` run automatically, did not depend on the value of skipFailure.

**Comment by puneet0191** [comment]
@vazsonyidl could u please send fix, thanks for reporting, I will merge and make a new release.

**Comment by eunicekokor** [comment]
@vazsonyidl @puneet0191 I am also running into this, there is also no mismatch percentage shown even though there is a new image generated in `diff`

**Comment by vazsonyidl** [comment]
@eunicekokor i will fix it tomorrow

**Comment by puneet0191** [comment]
Thanks guys for helping 😊

**Comment by vazsonyidl** [comment]
I do not have permission to contribute for this project. I am unable to push for a new branch created by me, so the solution should be.

` if (options.skipFailure === false) {
      assert(misMatch <= options.tolerance, "Screenshot does not match with the baseline " + baseImage + " when MissMatch Percentage is " + misMatch);
    }`

**should be replaced with:** 

`if (!options.skipFailure) {
      assert(misMatch <= options.tolerance, "Screenshot does not match with the baseline " + baseImage + " when MissMatch Percentage is " + misMatch);
    }`

This fixes this issue. This will assert de misMatch and tolerance by default, as it should behave. So the test will not passes if the mismatch is over tolerance. Please fix this. :100:

Thanks in advance!
